# Generated by Django 2.0.3 on 2018-03-18 09:05

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('machines', '0001_initial'),
        ('memberships', '0001_initial'),
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fablog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date and time', verbose_name='created at')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Closure date and time', null=True, verbose_name='closed at')),
                ('notes', models.TextField(blank=True, help_text='Notes on the Fablog', verbose_name='notes')),
            ],
            options={
                'verbose_name': 'fablog',
                'verbose_name_plural': 'fablogs',
                'ordering': ['-created_at', '-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='FablogBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cashier.Booking')),
                ('fablog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fablog.Fablog')),
            ],
            options={
                'verbose_name': 'associated Booking',
                'verbose_name_plural': 'associated Bookings',
            },
        ),
        migrations.CreateModel(
            name='FablogMemberships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2018, 1, 1), help_text='First day of membership', verbose_name='membership start date')),
                ('end_date', models.DateField(default=datetime.date(2018, 12, 31), help_text='Last day of membership', verbose_name='membership end date')),
                ('fablog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fablog.Fablog')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.Membership')),
            ],
            options={
                'verbose_name': 'service used',
                'verbose_name_plural': 'services used',
            },
        ),
        migrations.CreateModel(
            name='MachinesUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Machine use start time', verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, help_text='Machine use end time', null=True, verbose_name='end time')),
                ('fablog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fablog.Fablog')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.Machine')),
            ],
            options={
                'verbose_name': 'machine used',
                'verbose_name_plural': 'machines used',
            },
        ),
        migrations.CreateModel(
            name='MaterialsUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveSmallIntegerField(default=1, help_text='Units of Material used', verbose_name='units')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='price per unit', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price/unit')),
                ('fablog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fablog.Fablog')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.Material')),
            ],
            options={
                'verbose_name': 'material used',
                'verbose_name_plural': 'materials used',
            },
        ),
        migrations.AddField(
            model_name='fablog',
            name='bookings',
            field=models.ManyToManyField(through='fablog.FablogBookings', to='cashier.Booking', verbose_name='Bookings'),
        ),
    ]
