# Generated by Django 2.0.1 on 2018-03-02 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Booking date and time', verbose_name='Date & Time')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the booking', max_digits=10, verbose_name='amount')),
                ('notes', models.TextField(blank=True, help_text='Notes on Booking', null=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.PositiveSmallIntegerField(choices=[(0, 'Fablog'), (1, 'Donation'), (2, 'Store'), (3, 'Expenses'), (4, 'Correction')], default=0, unique=True)),
                ('description', models.CharField(blank=True, help_text='Description of Booking Type', max_length=250, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'booking type',
                'verbose_name_plural': 'booking types',
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date and time', verbose_name='created at')),
                ('cashier_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Cash account creation date and time', verbose_name='cash account date')),
            ],
            options={
                'verbose_name': 'cash count',
                'verbose_name_plural': 'cash counts',
                'ordering': ['-cashier_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCountNominals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(help_text='Count of None', verbose_name='count')),
                ('cash_count', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.CashCount')),
            ],
        ),
        migrations.CreateModel(
            name='CashNominal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Value of denomination', max_digits=7, unique=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'nominal',
                'verbose_name_plural': 'nominals',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of currency', max_length=20, unique=True, verbose_name='currency name')),
                ('fractional_name', models.CharField(help_text='Name of fractional currency', max_length=20, unique=True, verbose_name='fractional currency name')),
                ('abbreviation', models.CharField(help_text='Abbreviation of currency', max_length=3, unique=True, verbose_name='currency abbreviation')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the account', max_length=20, unique=True, verbose_name='account name')),
                ('default_account', models.NullBooleanField(default=True, help_text='Is this the default account for which bookings should be made?', unique=True, verbose_name='default account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Three letter short name for display.', max_length=3, verbose_name='short name')),
                ('long_name', models.CharField(help_text='Long name of payment method', max_length=50, verbose_name='long name')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
            },
        ),
        migrations.AddField(
            model_name='cashnominal',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.Currency'),
        ),
        migrations.AddField(
            model_name='cashcountnominals',
            name='cash_nominal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashier.CashNominal'),
        ),
        migrations.AddField(
            model_name='cashcount',
            name='cash',
            field=models.ManyToManyField(through='cashier.CashCountNominals', to='cashier.CashNominal', verbose_name='Cash'),
        ),
        migrations.AddField(
            model_name='cashcount',
            name='created_by',
            field=models.ForeignKey(help_text='Labmanager who created the cash account', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='cashcount',
            name='financial_account',
            field=models.ForeignKey(help_text='Associated account', on_delete=django.db.models.deletion.PROTECT, to='cashier.FinancialAccount', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.ForeignKey(help_text='Type of booking', on_delete=django.db.models.deletion.PROTECT, to='cashier.BookingType', verbose_name='booking type'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the booking', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='booking',
            name='financial_account',
            field=models.ForeignKey(help_text='Associated account', on_delete=django.db.models.deletion.PROTECT, to='cashier.FinancialAccount', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.ForeignKey(help_text='payment method', on_delete=django.db.models.deletion.PROTECT, to='cashier.PaymentMethod', verbose_name='payment method'),
        ),
    ]
