# Generated by Django 2.0.1 on 2018-03-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20180302_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
