# Generated by Django 2.0.1 on 2018-03-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('cashier', '0003_remove_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payed_byto',
            field=models.ForeignKey(default=1, help_text='User who payed/got payed', on_delete=django.db.models.deletion.PROTECT, to='members.Member', verbose_name='Payed by/to'),
            preserve_default=False,
        ),
    ]
