# Generated by Django 2.0.1 on 2018-03-02 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, help_text='price of service', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
            ],
        ),
    ]
