# Generated by Django 2.0.1 on 2018-03-02 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=255, verbose_name='first name')),
                ('full_name', models.CharField(blank=True, max_length=510, null=True, verbose_name='full name (automatic)')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2018, 1, 1), help_text='First day of current membership', verbose_name='membership start date')),
                ('end_date', models.DateField(default=datetime.date(2018, 12, 31), help_text='First day of current membership', verbose_name='membership start date')),
                ('legitimation', models.ImageField(blank=True, null=True, upload_to=members.models.legitimation_image_path)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.Booking')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Member')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Membership',
                'ordering': ['end_date'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='Membership',
            field=models.ManyToManyField(related_name='member', through='members.MembershipBookings', to='cashier.Booking', verbose_name='payments made'),
        ),
    ]
